<?php include 'header.php'; ?>

<h1>Solar System</h1>

<img src="Solar%20info.jpg">



<h2>The Sun</h2>
<img src="Sun%20info.jpg" alt="Sun info">

<p>
    The sun or sol is the centre celestial body(a Star) in are solar system which every planetary body orbits
    around to it gravitational pull, it is a massive nearly perfect sphere of hot plasma(15,000,000'c)
    which is generated by nuclear fusion reaction in it core. Sol surface radiates the energy mainly
    as visible light and infrared radiation.
</p>



<h2>Planetary Data Table</h2>

<table>
    <tr>
        <th>Planet/Dwarfs</th>
        <th>Distance from Sun (million km)</th>
        <th>Moons</th>
    </tr>

    <tr><td>Mercury</td><td>58</td><td>0</td></tr>
    <tr><td>Venus</td><td>108</td><td>0</td></tr>
    <tr><td>Earth</td><td>150</td><td>1</td></tr>
    <tr><td>Mars</td><td>228</td><td>2</td></tr>
    <tr><td>Jupiter</td><td>778</td><td>97</td></tr>
    <tr><td>Saturn</td><td>1429</td><td>83</td></tr>
    <tr><td>Uranus</td><td>2871</td><td>27</td></tr>
    <tr><td>Neptune</td><td>4498</td><td>14</td></tr>
    <tr><td>Pluto</td><td>5910</td><td>5</td></tr>
</table>

<h2> Planet Facts! </h2>

<ul>
    <li>The Solar system is roughly 4.5 billion years old </li>
    <li>Pluto isn't the only Dwarf planet in out solar system</li>
    <li>One Earth day is how long it take venus to make a full
        ration around the sun</li>
    <li>The moon Ganymede has more salt water than Earth</li>
    <li>The South Pole is as cold on the surface of Mars</li>
    <li>Saturn is the last planet that can be seen by
        the naked eye</li>
    <li>Only one spacecraft has flown by uranus</li>
    <li>Earth is the only planet not named after a god</li>
    <li>Pluto was named after the Roman god of the underworld</li>
    <li>Pluto is the largest dwarf planet</li>


</ul>





<?php include 'Footer.php'; ?>

